force-app/main/default/objects/Absense__c/Absense__c.object-meta.xml
<CustomObject>
    <label>Absense</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Absense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Absenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Absense__c/fields/Absense_Date__c.field-meta.xml
<CustomField>
    <fullName>Absense_Date__c</fullName>
    <label>Absense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Absense__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Absenses</relationshipLabel>
    <relationshipName>Absenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {
  
   @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts(String searchText) {
        return [
            SELECT Id, Name, Email, AppointmentDate__c
            FROM Contact
            WHERE Name LIKE : '%' + searchText + '%'
            OR Email LIKE : '%' + searchText + '%'
            WITH SECURITY_ENFORCED
            ORDER BY Name ASC
            LIMIT 4
        ];         
        }

   @AuraEnabled(cacheable=true)
    public static List<Contact> getBirthdays() {
        Date today = System.today();
        return [
            SELECT Id, Name, Birthdate, Email
            FROM Contact
            WHERE CALENDAR_MONTH(Birthdate) = :today.month()
            AND DAY_IN_MONTH(Birthdate) = :today.day()
            WITH SECURITY_ENFORCED
            LIMIT 50
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Absense__c> getAbsenses(String dateFilter) {
       Date today = System.today();
        Date startDate;
        Date endDate;

        // TODAY
        if (dateFilter == 'today') {
            startDate = today;
            endDate = today;
        }

        // THIS WEEK (based on org locale)
        else if (dateFilter == 'this_week') {
            startDate = today.toStartOfWeek();
            endDate = startDate.addDays(6);
        }

        // THIS MONTH (first day → last day)
        else if (dateFilter == 'this_month') {
            startDate = Date.newInstance(today.year(), today.month(), 1);
            endDate = startDate.addMonths(1).addDays(-1);
        }

        return [
            SELECT Id,
                   Name,
                   Absense_Date__c,
                   Contact__c,
                   Contact__r.Name
            FROM Absense__c
            WHERE Absense_Date__c >= :startDate
              AND Absense_Date__c <= :endDate
            WITH SECURITY_ENFORCED
            ORDER BY Absense_Date__c
            LIMIT 50
            
        ];
    }
}


     
  